### ISSUE TITLE
[LLM] Integrate Ollama for local model support

### ISSUE THREAD

**Issue by prof-schacht** [coairesearch/hierachical_safety_governor#10]
## Overview
Integrate Ollama for running local LLM models in agents. This enables realistic agent behavior without requiring API keys or external services.

## Goal
Create a flexible Ollama integration that allows agents to use any locally installed Ollama model for decision-making.

## Tasks
- [ ] Install and document Ollama setup requirements
- [ ] Create `adapters/ollama_adapter.py` with:
  - [ ] Model initialization and health checks
  - [ ] Prompt formatting for agent observations
  - [ ] Response parsing for action extraction
  - [ ] Error handling for connection issues
  - [ ] Model switching capabilities
- [ ] Extend `AutoGenAgentAdapter` to support Ollama backend
- [ ] Add configuration options in YAML:
  ```yaml
  agents:
    - id: firm_a
      impl: adapters.autogen_agent_adapter:AutoGenAgentAdapter
      params:
        autogen_agent:
          _factory: autogen.ConversableAgent
          name: "FirmA"
          llm_config:
            model: "ollama/llama3"
            temperature: 0.7
  ```
- [ ] Create prompt templates for different agent types
- [ ] Add performance monitoring (response time, token usage)

## Example Implementation Pattern
```python
class OllamaAdapter:
    def __init__(self, model_name="llama3", base_url="http://localhost:11434"):
        # Initialize Ollama connection
    
    def format_prompt(self, observation, role, history):
        # Convert observation to natural language prompt
    
    def get_action(self, prompt):
        # Send to Ollama, parse response for action
```

## Acceptance Criteria
- Agents can use any installed Ollama model
- Response parsing reliably extracts valid actions
- Graceful fallback when Ollama is unavailable
- Performance metrics logged for analysis
- Documentation includes Ollama setup guide

## Testing
- Test with multiple Ollama models (llama3, mistral, etc.)
- Test error scenarios (Ollama offline, invalid responses)
- Benchmark response times

**Priority: High** - Core feature for realistic agent behavior

## Dependencies
- Requires #8 and #9 to be completed
