### ISSUE TITLE
[LLM] Add frontier model support (OpenAI, Anthropic)

### ISSUE THREAD

**Issue by prof-schacht** [coairesearch/hierachical_safety_governor#11]
## Overview
Add support for frontier models (OpenAI, Anthropic) to enable testing with state-of-the-art LLMs and compare behavior across different model capabilities.

## Goal
Seamlessly integrate frontier models alongside Ollama, allowing mixed teams of local and API-based agents.

## Tasks
- [ ] Create unified LLM interface:
  ```python
  class LLMProvider(ABC):
      @abstractmethod
      async def get_completion(self, prompt, **kwargs): pass
  ```
- [ ] Implement providers:
  - [ ] `OpenAIProvider` - GPT-4, GPT-3.5 support
  - [ ] `AnthropicProvider` - Claude models
  - [ ] Unified configuration handling
- [ ] Add API key management:
  - [ ] Environment variable support
  - [ ] Config file with encryption
  - [ ] Key rotation capabilities
- [ ] Implement rate limiting and retry logic
- [ ] Add cost tracking per agent/experiment
- [ ] Extend YAML configuration:
  ```yaml
  agents:
    - id: firm_a
      impl: adapters.autogen_agent_adapter:AutoGenAgentAdapter
      params:
        autogen_agent:
          llm_config:
            provider: "openai"
            model: "gpt-4"
            api_key_env: "OPENAI_API_KEY"
            max_tokens: 150
            temperature: 0.7
  ```

## Cost Management Features
- Track tokens used per agent
- Set spending limits per experiment
- Generate cost reports
- Implement caching for repeated queries

## Acceptance Criteria
- Support for OpenAI and Anthropic models
- Automatic failover between providers
- Cost tracking accurate to $0.01
- Rate limiting prevents API errors
- Mixed local/API agent teams work smoothly

## Testing
- Mock API responses for unit tests
- Integration tests with real APIs (limited)
- Cost calculation verification
- Rate limit handling tests

**Priority: Medium** - Important for research comparison

## Dependencies
- Requires #10 to establish LLM patterns
