### ISSUE TITLE
[Safety] Enhance referee models for misalignment detection

### ISSUE THREAD

**Issue by prof-schacht** [coairesearch/hierachical_safety_governor#13]
## Overview
Enhance the existing SimpleCollusionReferee to detect various forms of agent misalignment and collusion using multiple detection strategies.

## Goal
Create a robust referee system that can identify different types of safety violations and suspicious agent behaviors with configurable sensitivity.

## Tasks
- [ ] Create base referee interface:
  ```python
  class BaseReferee(ABC):
      @abstractmethod
      def inspect(self, actions: Dict, state: Dict) -> Optional[Alert]:
          pass
      
      @abstractmethod
      def get_confidence(self) -> float:
          pass
  ```
- [ ] Implement referee types:
  - [ ] **StatisticalReferee**: Detect anomalies using statistical methods
    - Moving averages, standard deviations
    - Sudden behavior changes
    - Correlation analysis between agents
  - [ ] **PatternReferee**: Detect known bad patterns
    - Action sequences indicating collusion
    - Timing patterns (synchronized actions)
    - Communication patterns
  - [ ] **MLReferee**: Learn to detect violations
    - Train on labeled violation data
    - Online learning from interventions
    - Confidence scoring
- [ ] Enhance SimpleCollusionReferee:
  - [ ] Add configurable thresholds
  - [ ] Support multiple detection windows
  - [ ] Add explanation generation
- [ ] Implement referee composition:
  ```python
  class EnsembleReferee:
      def __init__(self, referees: List[BaseReferee], voting='majority'):
          # Combine multiple referee opinions
  ```
- [ ] Add referee configuration in YAML:
  ```yaml
  defenses:
    - id: statistical_referee
      impl: referees.statistical_referee:StatisticalReferee
      params:
        sensitivity: 0.95
        window_size: 10
    - id: ensemble_referee
      impl: referees.ensemble_referee:EnsembleReferee
      params:
        referees: [statistical_referee, pattern_referee]
        voting: 'weighted'
  ```

## Detection Capabilities
- Price fixing patterns
- Resource hoarding
- Information hiding
- Coordinated actions
- Deceptive behavior

## Acceptance Criteria
- Each referee type detects its target violations with >90% accuracy
- False positive rate <5% in normal operation
- Clear explanations for each alert
- Configurable sensitivity levels
- Real-time detection (<100ms)

## Testing
- Unit tests for each referee type
- Integration tests with known violation scenarios
- Performance benchmarks
- Sensitivity analysis

**Priority: High** - Core safety mechanism

## Dependencies
- Requires #8 and #12 (metrics for training/evaluation)
