### ISSUE TITLE
[CI/CD] Set up GitHub Actions pipeline

### ISSUE THREAD

**Issue by prof-schacht** [coairesearch/hierachical_safety_governor#27]
## Overview
Set up GitHub Actions CI/CD pipeline to automatically test, validate, and maintain code quality for every pull request and commit.

## Goal
Ensure code quality and prevent regressions through automated testing, linting, and validation on every code change.

## Tasks
- [ ] Create `.github/workflows/ci.yml`:
  ```yaml
  name: CI
  on:
    push:
      branches: [main, develop]
    pull_request:
      branches: [main]
  
  jobs:
    test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [3.8, 3.9, '3.10', 3.11]
  ```
- [ ] Add test job steps:
  - [ ] Checkout code
  - [ ] Install uv
  - [ ] Cache dependencies
  - [ ] Install project
  - [ ] Run pytest with coverage
  - [ ] Upload coverage reports
- [ ] Add linting job:
  - [ ] Run black (formatting)
  - [ ] Run ruff (linting)
  - [ ] Run mypy (type checking)
  - [ ] Check import sorting (isort)
- [ ] Add validation job:
  - [ ] Validate all YAML configs
  - [ ] Check documentation builds
  - [ ] Verify all examples run
  - [ ] Test CLI commands
- [ ] Add integration tests:
  - [ ] Test with Ollama (mock)
  - [ ] Run mini experiments
  - [ ] Verify metrics collection
  - [ ] Test export/import
- [ ] Create release workflow:
  ```yaml
  name: Release
  on:
    push:
      tags:
        - 'v*'
  ```
- [ ] Add automated checks:
  - [ ] Security scanning (bandit)
  - [ ] Dependency updates (dependabot)
  - [ ] License compliance
  - [ ] Documentation coverage

## Quality Gates
- All tests must pass
- Code coverage > 80%
- No linting errors
- Type checking passes
- All configs valid

## Performance Monitoring
```yaml
- name: Benchmark
  run: |
    python -m pytest tests/benchmarks --benchmark-only
    python scripts/compare_benchmarks.py
```

## Matrix Testing
- Python versions: 3.8, 3.9, 3.10, 3.11
- OS: Ubuntu, macOS, Windows
- Optional: with/without optional dependencies

## Caching Strategy
- Cache uv packages
- Cache test data
- Cache Ollama models (if used)
- Intelligent cache invalidation

## Status Badges
Add to README:
```markdown
![CI](https://github.com/coairesearch/hierachical_safety_governor/workflows/CI/badge.svg)
![Coverage](https://codecov.io/gh/coairesearch/hierachical_safety_governor/branch/main/graph/badge.svg)
```

## Acceptance Criteria
- CI runs in <5 minutes
- Clear failure messages
- Parallel job execution
- Automatic PR checks
- Protected main branch

## Testing
- Test CI on feature branch
- Verify all job steps
- Test failure scenarios
- Measure execution time

**Priority: High** - Ensures code quality

## Dependencies
- After #9 (unit tests exist)
- Requires test suite to be meaningful
