### ISSUE TITLE
[Environments] Add Commons and Auction games

### ISSUE THREAD

**Issue by prof-schacht** [coairesearch/hierachical_safety_governor#32]
## Overview
Add 1-2 additional game environments that demonstrate different failure modes (collusion, resource depletion, etc).

## Goal
Create simple, self-contained environments that follow the same pattern as PriceGame to test different safety scenarios.

## Tasks
- [ ] Create `environments/commons_game.py`:
  ```python
  class CommonsGame(gym.Env):
      """Tragedy of commons - agents harvest from shared resource"""
      def __init__(self, n_agents=5, resource_capacity=100):
          # Setup shared resource with regeneration
          
      def step(self, actions):
          # Each agent harvests, resource depletes/regenerates
          # Nash: everyone overuses → resource crashes
          # Social optimum: sustainable harvesting
  ```
- [ ] Add `environments/auction_game.py` (optional):
  ```python
  class AuctionGame(gym.Env):
      """Sealed bid auction - tests bid collusion"""
      # Nash: competitive bidding
      # Collusion: rotation/suppression
  ```
- [ ] Register in `environments/__init__.py`
- [ ] Create example configs:
  ```yaml
  # configs/commons_test.yaml
  base_env: Commons-v0
  agents:
    - id: harvester_1
      impl: adapters.autogen_agent_adapter:AutoGenAgentAdapter
      params:
        autogen_agent:
          llm_config: 
            model: "ollama/llama3"
  ```

## Keep It Simple
- Each environment ~100-150 lines max
- Clear documentation of Nash equilibrium
- No base classes or abstractions needed
- Focus on demonstrating specific failure modes

## Acceptance Criteria
- New environments work with existing orchestrator
- Clear game theory dynamics (Nash vs social optimum)
- Can demonstrate safety violations
- Easy to understand and modify

## Testing
```bash
python run_once.py --config configs/commons_test.yaml
# Should see resource depletion without governor
```

**Priority: High** - Need diverse test scenarios
