### ISSUE TITLE
[Governors] Simple hierarchical oversight experiment

### ISSUE THREAD

**Issue by prof-schacht** [coairesearch/hierachical_safety_governor#35]
## Overview
Create a simple hierarchical governor structure to test multi-level oversight patterns.

## Goal
Enable experiments with hierarchical safety governance without complex abstractions.

## Tasks
- [ ] Create `governors/multi_level.py`:
  ```python
  class TwoLevelGovernor:
      """Simple two-tier governor for testing hierarchy"""
      def __init__(self, local_referees, consensus_threshold=0.5):
          self.local_referees = local_referees  # Dict {zone: referee}
          self.threshold = consensus_threshold
          
      def intervene(self, env):
          # Collect alerts from local referees
          alerts = {}
          for zone, referee in self.local_referees.items():
              if hasattr(referee, 'alert_flag') and referee.alert_flag:
                  alerts[zone] = referee.last_alert
          
          # Simple consensus: if >threshold zones alert, global action
          if len(alerts) > len(self.local_referees) * self.threshold:
              print(f"[Global Governor] System-wide intervention")
              env.reset()  # Or other global action
              return True
              
          # Otherwise, local actions only
          for zone, alert in alerts.items():
              print(f"[Local Governor] Zone {zone} intervention")
              # Zone-specific action
          return False
  ```
- [ ] Add zone concept to environments (optional):
  ```python
  # In commons_game.py
  def get_zones(self):
      # Split agents into regions/groups
      n_zones = 2
      agents_per_zone = self.n_agents // n_zones
      return {
          f"zone_{i}": self.agents[i*agents_per_zone:(i+1)*agents_per_zone]
          for i in range(n_zones)
      }
  ```
- [ ] Create hierarchical config:
  ```yaml
  # configs/hierarchical_test.yaml
  defenses:
    - id: zone_a_referee
      impl: referees.simple_collusion_referee:SimpleCollusionReferee
      params:
        threshold: 6  # More lenient locally
        
    - id: zone_b_referee
      impl: referees.resource_guardian:ResourceGuardian
      
    - id: global_governor
      impl: governors.multi_level:TwoLevelGovernor
      params:
        local_referees:
          zone_a: zone_a_referee
          zone_b: zone_b_referee
        consensus_threshold: 0.5
  ```

## Keep It Simple
- Start with 2 levels (local + global)
- Simple aggregation rules
- Clear intervention hierarchy
- Easy to extend later

## Research Questions to Test
- Do local interventions prevent global crises?
- When is hierarchy better than flat oversight?
- How do agents adapt to multi-level governance?

## Acceptance Criteria
- Can compose existing referees hierarchically
- Clear delegation of interventions
- Works with existing environments
- Easy to experiment with different structures

## Testing
```bash
# Compare flat vs hierarchical
python run_once.py --config configs/flat_governor.yaml
python run_once.py --config configs/hierarchical_test.yaml
# Analyze intervention patterns
```

**Priority: Medium** - Enables key research questions
